#!/bin/bash

while (( $# > 0 ));do
    case ${1} in
        -u)
            userid=${2}
            shift 1
        ;;
        -p)
            password=${2}
            shift 1
        ;;
        -d)
            domain=${2}
            shift 1
        ;;
        -h)
            hostname=${2}
            shift 1
        ;;
        -i)
            ip_addr=${2}
            shift 1
        ;;
    esac
    shift 1
done

if [ -z "$userid" ] || [ -z "$password" ] || [ -z "$domain" ] || [ -z "$hostname" ];then
    echo onamae_ddns -u userid -p password -d domain -h hostname [-i ip_addr]
    exit
fi

if [ -z "$ip_addr" ];then
    ip_addr=$(curl -s inet-ip.info)
fi

if [ "`dig ${hostname}.${domain} +short @01.dnsv.jp`" = "$ip_addr" ];then
    echo "no update"
    exit
fi

if [ ! `(
        echo -e "LOGIN\nUSERID:${userid}\nPASSWORD:${password}\n."
        sleep 0.1
        echo -e "MODIP\nHOSTNAME:${hostname}\nDOMNAME:${domain}\nIPV4:${ip_addr}\n."
        sleep 0.1
        echo -e "LOGOUT\n."
    ) | openssl s_client -connect ddnsclient.onamae.com:65010 -verify_quiet -quiet |  grep -c 000` = "4" ];then
    echo "error"
    exit -1
fi
